name: Linux

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        luaVersion: ["5.4.1", "5.1.5", "luajit-2.1.0-beta3"]
        luarocksVersion: ["3.5.0", "3.0.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: ${{ matrix.luarocksVersion }}

      - name: Tests
        run: |
          luarocks build --local tests/example1/test-1.0-1.rockspec
          luarocks build --local tests/example2/test-1.0-1.rockspec
