name: Linux

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Installation
        run: |
          sudo apt update -y
          sudo apt install -y luarocks

      - name: Tests
        run: |
          luarocks build tests/example1/test-1.0-1.rockspec
          luarocks build tests/example2/test-1.0-1.rockspec
