name: Windows

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        version: ["2.4.4", "3.5.0"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: ${{ matrix.version }}

      - name: Tests
        run: |
         luarocks build tests/example1/test-1.0-1.rockspec
         luarocks build tests/example2/test-1.0-1.rockspec
