name: Windows

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Tests
        run: |
          Invoke-WebRequest "http://luarocks.github.io/luarocks/releases/luarocks-3.5.0-win32.zip" -UseBasicParsing -OutFile ./luarocks.zip
          Expand-Archive ./luarocks.zip -DestinationPath ./luarocks
          Push-Location ./luarocks/luarocks-3.5.0-win32
          ./install.bat /P temp /CONFIG temp/luarocks
          temp/luarocks.exe install --local --verbose rockspecs/example1-1.0-1.rockspec
          lua -e "print(require(\"example1.hello\"))"
